# This is a template file for creating Kubernetes secrets.
# DO NOT apply this directly to your cluster as it contains placeholder values.
# Instead, fill in the actual values and use kubectl create secret command or
# a secure secrets management tool like Vault or AWS Secrets Manager.

apiVersion: v1
kind: Secret
metadata:
  name: pocketlegal-secrets
type: Opaque
stringData:
  # Database connection
  mongodb-uri: "mongodb://user:password@mongodb:27017/pocketlegal?authSource=admin"
  
  # JWT Authentication
  jwt-secret: "replace_with_actual_jwt_secret"
  
  # OAuth Credentials
  google-client-id: "replace_with_actual_google_client_id"
  google-client-secret: "replace_with_actual_google_client_secret"
  facebook-app-id: "replace_with_actual_facebook_app_id"
  facebook-app-secret: "replace_with_actual_facebook_app_secret"
  linkedin-client-id: "replace_with_actual_linkedin_client_id"
  linkedin-client-secret: "replace_with_actual_linkedin_client_secret"
  
  # Payment Gateway
  stripe-secret-key: "replace_with_actual_stripe_secret_key"
  stripe-webhook-secret: "replace_with_actual_stripe_webhook_secret"
  
  # Email Credentials
  email-user: "replace_with_actual_email_user"
  email-password: "replace_with_actual_email_password"

# Note: In a production environment, use a secure method to manage secrets:
# 1. AWS Secrets Manager
# 2. HashiCorp Vault
# 3. Google Secret Manager
# 4. Azure Key Vault
# 5. Kubernetes External Secrets Operator 